### ISSUE TITLE
Colombia TV not installing in Android 

### ISSUE THREAD

**Issue by alexsotocx** [diegofn/wiiego-kodi-addons#15]
Hi

When I try to install the add-on from the repository itself, it closes the window of the installation but nothing happen, I don't get any notification of completion but also no error. But it doesnt get installed.
It's actually supported on Android?

Env
Android TV - Android M

The installation is plain Kodi 17.6

Estamos hablando :)

**Comment by diegofn** [comment]
Please download the latest version of the repository bit.ly/ColombiaTVRepo2

**Comment by diegofn** [comment]
Yes, the addon has AndroidTV support. Please comment me if it works for you.

**Comment by alexsotocx** [comment]
Hola, no nada me sigue sin funciona :/ Voy a seguir intentando para ver que pasa.

**Comment by diegofn** [comment]
Intenta desinstalar tanto el addon como el repositorio y a continuación, descarga e instala el repositorio de bit.ly/ColombiaTVRepo2

**Comment by alexsotocx** [comment]
Ya con ese si funciono, Muchas gracias. te quería preguntar tambien. Todo el contenido es por streaming cierto? No hay nada de torrents incluidos? Es que vivo Fuera del país y Acá joden mucho por torrents y no me quiero ganar una multa.

Gracias por el excelente addon

**Comment by diegofn** [comment]
Hola, todo son links de streaming, el soporte de torrents en Kodi es algo complicado e inestable. Gracias por usar el addon :-)

**Comment by jacirbadillo** [comment]
Hola, me está pasando lo mismo, estoy intentando instalar con la versión que está en el enlace y no hace nada.  Alguna idea?
