### ISSUE TITLE
RCN y Caracol no funcionan.

### ISSUE THREAD

**Issue by soycamiloypunto** [diegofn/wiiego-kodi-addons#17]
He sido un amante de este addon, es mi preferido para ver canales regionales en colombia gracias a Kodi. 

desde que actualicé a Kodi 18 estable no funcionan los canales.

**Comment by diegofn** [comment]
Hola,

Te cuento que actualice tres dispositivos, Mac, Android y AndroidTV y en todos me funcionaron bien. Si quieres desinstala el addon y vuelves y lo instalas desde el repositorio y me cuentas.
