### ISSUE TITLE
Channels not working 2019

### ISSUE THREAD

**Issue by gwzapata** [diegofn/wiiego-kodi-addons#18]
I have been using colombia TV on kodi so my father can watch caracol, rcn, teleantioquia, telemedellin. It has not been working I tried today 2/21/2019. It just goes around in a circle and does not open the page.

**Comment by jgomer2001** [comment]
It works like a charm for me. I've been using vesion 1.6.3 for months. Congrats @diegofn

**Comment by diegofn** [comment]
Thanks for your feedback.
