### ISSUE TITLE
Canales sin señal aún con VPN a Colombia

### ISSUE THREAD

**Issue by fantore** [diegofn/wiiego-kodi-addons#19]
ola Diego.

Primero que todo agradeciendo este muy útil addon.

Por mucho tiempo debía esperar las actualizaciones de versión para poder tener por algún tiempo señal, pensaba que fallaba por algún bloqueo geografico a IPs de fuera del país.

Ahora con una VPN a Colombia muchos canales no funcionan.

Qué recomiendas? Debes actualizar los links a canales?

Cómo te puedo ayudar en las pruebas?

Gracias por este addon y de antemano gracias por tu ayuda,.

**Comment by fantore** [comment]
Hola Diego.
Esperando tu respuesta... sigues mantiendo este addon? Ojalá puedes continuar desarrollándolo. En lo que pueda ayudar con gusto.

Una sugerencia. Puedes adicionar "CARACOL AHORA"?.  Dan las noticias en vivo y programas periodísticos que no se ven en el canal princioal. pareciese que se purde ver fuera de Colombia.

Este es el link "podado" para navegadores.

https://mdstrm.com/live-stream/58dc3d471cbe05ff3c8e463e

Gracias por tu atención.

**Comment by diegofn** [comment]
Gracias por la sugerencia pero el link que me enviaste no permite el consumo sin una URL, revisaré Caracol Ahora y te contaré.
