### ISSUE TITLE
NOthing is working

### ISSUE THREAD

**Issue by porroto** [diegofn/wiiego-kodi-addons#20]
This used to be a really nice addon to use on Kodi. but unfortunately is not working anymore!

**Comment by mflorezm** [comment]
The addon is no longer working.

**Comment by diegofn** [comment]
Hello, is the addon not working on Kodi 18? what error is getting?
We are working in a new version for Kodi 19+ you can download it and test if you can. The local channels are working.

**Comment by porroto** [comment]
Links and channels are not working! Colombian Movies works fine but not the
channels

**Comment by diegofn** [comment]
Ok, If you use Kodi 19, you can download the github version thats works with new channels including Winsports mas

**Comment by mflorezm** [comment]
Dear Diego, I'm using Kodi 18 on a RPI3, but the Caracol and RCN stopped working a few days ago. Teleantioquia and other channels stopped working several months ago. Can you issue a new version release in zip? i really don't know how to create the kodi zip from github. Thanks.

**Comment by diegofn** [comment]
Hello @mflorezm 

Please download the following link
https://github.com/diegofn/wiiego-kodi-addons/raw/master/repo/plugin.video.colombiatv/plugin.video.colombiatv-1.7-dev.zip

This is the dev version, remember that it only works on Kodi 19.
