### ISSUE TITLE
Claro DASH

### ISSUE THREAD

**Issue by okidokios** [diegofn/wiiego-kodi-addons#21]
Hola oye una duda ya no funcionan los claro dash wv? me gusto tu addon solo que estaba buscando como reproducir los dash en kodi y vi tu tema pidiendo ayuda a peak y creo un plugin pero no funciona ya, queria saber si ya no funciona y por eso removiste los claro mpd o preferiste los hls? espero me puedas ayudar 

saludos

**Comment by diegofn** [comment]
Hola, ya no funcionan, el hoster decidió implementar muchos controles para los certificados y ya no funciona por lo que decidí cambiarlo por HLS.

**Comment by okidokios** [comment]
oh entiendo, yo queria ver los dash! :(, muchas gracias por la respuesta y me encanta tu addon! 👍

**Comment by diegofn** [comment]
Gracias por utilizarlo.
