### ISSUE TITLE
Some colombiaTV channels not watchable

### ISSUE THREAD

**Issue by jgomer2001** [diegofn/wiiego-kodi-addons#22]
Hi Diego,

I cannot watch some of the channels listed in the addon, for example, Señal Colombia. After clicking on the channel, the blue wheel appears for a short time and nothing else happens. The same occurs for other channels. They were working fine time ago...  I hope you can manage some time to check what's wrong

Env: Kodi Leia 18.9 on Ubuntu 18 and fire tv stick

**Comment by diegofn** [comment]
Hello, 

Please update to the 1.7.0 version Señal Colombia is working right now.

**Comment by jgomer2001** [comment]
Hi @diegofn , I updated to kodi 19, tried to install the add-on but I'm getting "dependency on xmbc.python 2.14.0 could not be satisfied", any idea?

**Comment by diegofn** [comment]
Hello, you need to install the 1.7.0 with python3 support
